server:
  port: 8081
logging:
    level:
        es.iesjandula: INFO
    file:
        name: C:\logs\reaktor_reaktor_printersclient.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
reaktor:
  publicKeyFile: C:\claves\public_key.pem
  fixedDelayString:
    sendPrinters: "60000"
    print: "30000"
  bannedPrinters: Microsoft XPS Document Writer, Fax, OneNote for Windows 10, Send To OneNote 2016, AnyDesk Printer, OneNote (Desktop)
  printers_server_url: "http://localhost:8082/"
  firebase_server_url: "http://localhost:8083/"
  uidFile: C:\claves\uid_file.txt
  threadsNumber: 10