server:
  port: 8081
logging:
  level:
    es.iesjandula: INFO
  file:
    name: C:\logs\reaktor_reaktor_printersclient.log
    max-size: 1MB
    max-history: 10
    total-size-cap: 10MB
reaktor:
  publicKeyFile: C:\claves\public_key.pem
  cron: "*/30 * 7-20 * * MON-SUN"
  bannedPrinters: Microsoft XPS Document Writer, Fax, OneNote for Windows 10, Send To OneNote 2016, AnyDesk Printer, OneNote (Desktop), Microsoft Print to PDF, Adobe PDF, d-COPIA 7001MF, EPSON XP-205 207 Series, mi impresora
  printers_server_url: http://localhost:8082/
  firebase_server_url: http://localhost:8083/
  notifications_server_url: http://localhost:8088/
  school_manager_server_url: http://localhost:8087/
  clientId: CLIENTE_IMPRESORA
  threadsNumber: 10
  http_connection_timeout: 30000
  print_timeout: 60000