server:
  port: 8081
printer:
  sendPrinters:
    fixedDelayString: "5000"
  print:
    fixedDelayString: "5000"
  banned: Microsoft XPS Document Writer, Fax, OneNote for Windows 10, Send To OneNote 2016, Microsoft Print to PDF, AnyDesk Printer, OneNote (Desktop)
  server:
    url: "http://localhost:8082/"