server:
  port: 8081
logging:
    level:
        root: INFO
    file:
        name: C:\logs\reaktor_reaktor_printersclient.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  fixedDelayString:
    sendPrinters: "5000"
    print: "5000"
  bannedPrinters: Microsoft XPS Document Writer, Fax, OneNote for Windows 10, Send To OneNote 2016, Microsoft Print to PDF, AnyDesk Printer, OneNote (Desktop)
  printers_server_url: "https://api.iesjandula.es/"
  firebase_server_url: "https://api.iesjandula.es/"
  uidFile: C:\claves\uid_file.txt
  threadsNumber: 10